language: node_js
node_js:
  - 6
addons:
  ssh_known_hosts: antoinedeveyrac.io
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_41e16542647c_key -iv $encrypted_41e16542647c_iv
    -in deploy-key.enc -out deploy-key -d
  - npm rebuild node-sass
script:
  - npm test
  - npm run build
after_success:
  - bash bin/deploy.sh
