language: node_js
node_js:
- 6
addons:
  ssh_known_hosts: antoinedeveyrac.io
cache:
  directories:
  - node_modules
before_install:
  - npm rebuild node-sass
before_deploy:
  - echo "Starting SSH session"
  - openssl aes-256-cbc -K $encrypted_41e16542647c_key -iv $encrypted_41e16542647c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval `ssh-agent -s`
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh -o StrictHostKeyChecking=no -l $HOST $DEPLOY_HOST "ls -lah /var/www/dev.antoinedeveyrac.io/"
script:
- npm test
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $USER@$DEPLOY_HOST:/var/www/dev.antoinedeveyrac.io
  on:
    branch: master
